# Generated by Django 4.1.13 on 2026-06-08 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oe_inventory_py_web', '0002_oeesdelegations_cpostal_oeesdelegations_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oeesdelegations',
            name='cpostal',
        ),
        migrations.RemoveField(
            model_name='oeesdelegations',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='oeesdelegations',
            name='poblacion',
        ),
        migrations.RemoveField(
            model_name='oeesdelegations',
            name='provincia',
        ),
    ]
