# Generated by Django 4.1.13 on 2026-06-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oe_inventory_py_web', '0003_remove_oeesdelegations_cpostal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oeesdelegations',
            name='cpostal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='oeesdelegations',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='oeesdelegations',
            name='poblacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='oeesdelegations',
            name='provincia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
