# Generated by Django 4.1.13 on 2026-06-09 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oe_inventory_py_web', '0004_oeesdelegations_cpostal_oeesdelegations_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OeesProvinces',
            fields=[
                ('id_province', models.AutoField(primary_key=True, serialize=False)),
                ('province', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'oees_provinces',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='oeesdelegations',
            name='provincia',
            field=models.ForeignKey(blank=True, db_column='provincia', null=True, on_delete=django.db.models.deletion.SET_NULL, to='oe_inventory_py_web.oeesprovinces'),
        ),
    ]
