# Generated by Django 4.1.13 on 2026-06-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oe_inventory_py_web', '0005_oeesprovinces_alter_oeesdelegations_provincia'),
    ]

    operations = [
        migrations.AddField(
            model_name='oeesdelegations',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oeesdelegations',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
