# Generated by Django 4.1.13 on 2026-06-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oe_inventory_py_web', '0006_oeesdelegations_latitude_oeesdelegations_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='oeesdelegations',
            name='activo',
            field=models.IntegerField(default=1),
        ),
    ]
