# Generated by Django 4.1.13 on 2026-06-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oe_inventory_py_web', '0007_oeesdelegations_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='oeesprinters',
            name='bw_page_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='oeesprinters',
            name='color_page_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='oeesprinters',
            name='contract_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
