# Generated by Django 4.1.13 on 2026-06-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oe_inventory_py_web', '0008_oeesprinters_bw_page_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oeesdevices',
            name='mobile_line',
            field=models.IntegerField(default=0),
        ),
    ]
