# Generated by Django 4.1.13 on 2026-06-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oe_inventory_py_web', '0009_alter_oeesdevices_mobile_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='not_returned',
            field=models.IntegerField(default=0, verbose_name='not_returned'),
        ),
    ]
