# Generated by Django 4.1.13 on 2026-06-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oe_inventory_py_web', '0010_customuser_not_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='omada',
            field=models.IntegerField(default=0, verbose_name='omada'),
        ),
    ]
