# Generated by Django 4.1.13 on 2026-06-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oe_inventory_py_web', '0011_customuser_omada'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nebula',
            field=models.IntegerField(default=0, verbose_name='nebula'),
        ),
    ]
