# Generated by Django 4.1.13 on 2026-06-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oe_inventory_py_web', '0014_swap_omada_net_overview_nebula'),
    ]

    operations = [
        migrations.CreateModel(
            name='OeesMeetingRoom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meet_id', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('org_email', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('occupied', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'oees_meeting_room',
                'managed': True,
            },
        ),
    ]
