# Generated by Django 4.1.13 on 2026-06-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oe_inventory_py_web', '0015_oeesmeetingroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='oeesmeetingroom',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oeesmeetingroom',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
