# Generated by Django 4.1.13 on 2026-07-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oe_inventory_py_web', '0016_oeesmeetingroom_end_time_oeesmeetingroom_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='oeesfiberlines',
            name='fee',
            field=models.FloatField(default=0),
        ),
    ]
