# Generated by Django 4.1.13 on 2026-07-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oe_inventory_py_web', '0017_oeesfiberlines_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='oeesmobilelines',
            name='desc_tarif',
            field=models.CharField(blank=True, db_column='DescTarif', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='oeesmobilelines',
            name='fee',
            field=models.FloatField(default=0),
        ),
    ]
