# Generated by Django 4.1.13 on 2026-07-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oe_inventory_py_web', '0018_oeesmobilelines_desc_tarif_oeesmobilelines_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='oeesincorporations',
            name='sweatshirt_size',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
