# Generated by Django 4.1.13 on 2026-07-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oe_inventory_py_web', '0019_oeesincorporations_sweatshirt_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='oeesincorporations',
            name='email',
            field=models.CharField(blank=True, db_column='personal_email', max_length=254, null=True),
        ),
    ]
