# Generated by Django 4.1.13 on 2026-07-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oe_inventory_py_web', '0020_oeesincorporations_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='oeesincorporations',
            name='email_processed',
            field=models.IntegerField(default=0),
        ),
    ]
