# Generated by Django 4.1.13 on 2026-07-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oe_inventory_py_web', '0021_oeesincorporations_email_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='oeesincorporations',
            name='left_mouse',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
