# Generated by Django 4.1.13 on 2026-07-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oe_inventory_py_web', '0022_oeesincorporations_left_mouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='OeesDevicesType',
            fields=[
                ('id_device_type', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'oees_devices_type',
                'managed': True,
            },
        ),
    ]
