# Generated by Django 4.1.13 on 2026-07-15 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oe_inventory_py_web', '0023_oeesdevicestype'),
    ]

    operations = [
        # 1) Make the column NULLable first (it was NOT NULL), otherwise the
        #    cleanup UPDATE below can't set NULL.
        migrations.AlterField(
            model_name='oeesdevices',
            name='type',
            field=models.CharField(max_length=25, null=True, blank=True),
        ),
        # 2) Null-out any value that is empty or not a valid oees_devices_type id,
        #    so converting the column to int + adding the FK doesn't fail on
        #    bad/legacy data.
        migrations.RunSQL(
            sql=(
                "UPDATE oees_devices SET type = NULL "
                "WHERE type = '' "
                "OR type NOT IN (SELECT id_device_type FROM oees_devices_type);"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        # 3) Now turn it into the ForeignKey (int column + FK constraint).
        migrations.AlterField(
            model_name='oeesdevices',
            name='type',
            field=models.ForeignKey(blank=True, db_column='type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='oe_inventory_py_web.oeesdevicestype'),
        ),
    ]
