# Generated by Django 4.1.13 on 2026-07-15 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oe_inventory_py_web', '0024_alter_oeesdevices_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='oeesorders',
            name='id_type',
            field=models.ForeignKey(blank=True, db_column='id_type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='oe_inventory_py_web.oeesdevicestype'),
        ),
    ]
