# Generated by Django 4.1.13 on 2026-07-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oe_inventory_py_web', '0025_oeesorders_id_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='oeesincorporations',
            name='kit_mouse_keyb',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
