"""
Django settings for oe_inventory project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from django.core.exceptions import ImproperlyConfigured
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_dotenv(path):
    """Minimal .env loader (stdlib only) so secrets stay out of the codebase."""
    if not path.exists():
        return
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, _, value = line.partition('=')
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


_load_dotenv(BASE_DIR / '.env')


def _require_env(name):
    value = os.environ.get(name)
    if not value:
        raise ImproperlyConfigured(f"Missing required environment variable: {name}")
    return value


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = _require_env('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if host.strip()
]

# Origins trusted for CSRF (e.g. https://your-domain, https://*.elasticbeanstalk.com).
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]


# Application definition

INSTALLED_APPS = [
    'oe_inventory_py_web.apps.OeInventoryPyWebConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'oe_inventory_py_web.middleware.BlockReaderExportMiddleware',
    'oe_inventory_py_web.middleware.TrackActiveUserMiddleware',
]

# Send the origin as Referer on cross-origin requests (Django's default
# 'same-origin' sends none, which makes OpenStreetMap tile servers reject the
# map tiles with a 403 "Referer is required"). This is the modern browser
# default and does not leak the full URL path cross-origin.
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# Serve static files with WhiteNoise when it's installed (e.g. in production on
# Elastic Beanstalk). Kept optional so local dev works without the package.
try:
    import whitenoise  # noqa: F401
    _WHITENOISE_AVAILABLE = True
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')  # right after SecurityMiddleware
except ImportError:
    _WHITENOISE_AVAILABLE = False

# HTTPS hardening behind the load balancer. Enabled only when
# DJANGO_SECURE_SSL_REDIRECT=True (set it on the production environment) so it
# never interferes with local development or the test suite.
if os.environ.get('DJANGO_SECURE_SSL_REDIRECT', 'False') == 'True':
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

ROOT_URLCONF = 'oe_inventory.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'oe_inventory_py_web.context_processors.mdi_status_counters',
                'oe_inventory_py_web.context_processors.manual_help',
            ],
        },
    },
]

WSGI_APPLICATION = 'oe_inventory.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', 'oees_inventory'),
        'USER': _require_env('DB_USER'),
        'PASSWORD': _require_env('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '3306'),
    }
}

# When running the test suite, use a fast in-memory SQLite database so tests
# don't require a running MySQL server.
if 'test' in sys.argv:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': ':memory:',
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'oe_inventory_py_web' / 'static',
]
# Target for `collectstatic` (required in production / on Elastic Beanstalk).
STATIC_ROOT = BASE_DIR / 'staticfiles'

# In production WhiteNoise serves static files. We use "finders" mode so it
# serves them directly from the app's static dirs even if `collectstatic` hasn't
# populated STATIC_ROOT, and we DON'T use the hashed-manifest storage (a missing
# manifest entry would raise a 500 on render).
if _WHITENOISE_AVAILABLE and not DEBUG:
    WHITENOISE_USE_FINDERS = True

# Uploaded files (e.g. staff documents)
# https://docs.djangoproject.com/en/5.2/topics/files/
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Store uploaded media (staff_docs PDFs) on S3 when a bucket is configured.
# The local filesystem on Elastic Beanstalk is not persistent, so production
# must use S3. Credentials are taken from env vars or the instance IAM role.
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
if AWS_STORAGE_BUCKET_NAME:
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', '')
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'oe_inventory_py_web.CustomUser'

LOGIN_REDIRECT_URL = 'mdi_home'

LOGIN_ON_GET = True

LOGIN_URL = 'login'

USE_THOUSAND_SEPARATOR = True


# Logging
# https://docs.djangoproject.com/en/5.2/topics/logging/
# Level is configurable via the DJANGO_LOG_LEVEL environment variable.

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} [{levelname}] {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'oe_inventory_py_web': {
            'handlers': ['console'],
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
}


# Email is sent through the Resend API (oe_inventory_py_web.email_backend).
# The API key and sender come from the environment — never hardcode them.
# The "from" address must use a domain verified in your Resend account.
# https://resend.com/docs

EMAIL_BACKEND = 'oe_inventory_py_web.email_backend.ResendEmailBackend'
RESEND_API_KEY = os.environ.get('RESEND_API_KEY', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'onboarding@resend.dev')

# Recipient for the staff inventory reports (the People department).
STAFF_REPORT_RECIPIENT = os.environ.get('STAFF_REPORT_RECIPIENT', '')
